include ../../bin/Makefile.defs

LIBRARY = libcache.a
OBJECT  =
SRCS    = cache_init.c cache.c cache_wb.c l1d_cache.c l1i_cache.c     \
	  l2cache.c cache_help.c cache_bus.c cache_cpu.c cache_stat.c \
	  system.c cache_debug.c pipeline.c ubuf.c syscontrol.c


include ../../bin/Makefile.rules
