include ../../bin/Makefile.defs
 
LIBRARY = libio.a
OBJECT  = 

SRCS    = addr_map.c io_generic.c pci.c realtime_clock.c scsi_controller.c \
	  ahc.c scsi_bus.c scsi_disk.c disk_mech.c disk_cache.c disk_storage.c
 

include ../../bin/Makefile.rules

